Support testing against Python 3.13
beeware/briefcase pull request #1495
Opened 2023-10-16 19:15 UTC by rmartin16

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2023-10-17 05:54 UTC, freakboy3742 requested changes
Content of the PR looks good; although it's missing the setup.cfg metadata declaring Py3.13 compatibility. 

On top of that, I think we should hold off merging until coverage and CI is passing. We have a higher threshold for failures on dev releases, but as we're still early in the 3.13 cycle, I think we can afford to hold off until there's basic support in place.

2023-10-17 14:01 UTC, rmartin16 commented
Agreed; I was mostly just curious where support stands. At a minimum, we're waiting on a release of `coverage`.

2024-02-16 22:32 UTC, rmartin16 commented
Pytest [8.0.1](https://github.com/pytest-dev/pytest/releases/tag/8.0.1) released with the needed fix. I also added the classifier for Python 3.13.

2024-02-17 00:59 UTC, freakboy3742 approved these changes
Looks fairly straightforward; Approved on the basis that it does what it says on the tin.

As a follow up to this - we should probably turn on macOS ARM64 testing as well. That will start to explode the size of the CI matrix to absurd levels - but we can probably cut back on doing *every* python version on *every* OS, and limit ourselves to "min and max versions" (or min, max and dev) on every OS, and every version on *one* OS (probably linux, given there are more available runners).

2024-02-17 00:59 UTC, merged