Fix minor holes in PEP-508 name validation
beeware/briefcase pull request #1762
Opened 2024-04-29 17:59 UTC by rmartin16

## Changes
- This resolves a hole in the recommended implementation of name validation from [PEP-508](https://peps.python.org/pep-0508/#names) to avoid allowing non-ASCII values.
```
The regex (run with re.IGNORECASE) is:

^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$
```
- The implementation of `re.IGNORECASE` is ostensibly coercing the case of the input because it will match on non-ASCII.
  - This matters for, at least, İ ([0x130](https://everythingfonts.com/unicode/0x0130)) and K ([0x212a](https://everythingfonts.com/unicode/0x212A)).
```pycon
>>> import re
>>> PEP508_NAME_RE = re.compile(r"^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$", re.IGNORECASE)
>>> 
>>> bool(PEP508_NAME_RE.match("helloworld"))
True
>>> bool(PEP508_NAME_RE.match("İstanbul"))
True
>>> bool(PEP508_NAME_RE.match("Kelvin"))
True
>>> bool(PEP508_NAME_RE.match("Æolia"))
False
>>> bool(PEP508_NAME_RE.match("jalapeño"))
False
>>> bool(PEP508_NAME_RE.match("Beyoncé"))
False
>>> bool(PEP508_NAME_RE.match("naïve"))
False
```

## Related
- https://github.com/beeware/briefcase/issues/1011

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2024-04-29 18:25 UTC, rmartin16 commented
PEP-508 says PyPI uses this regex...and indeed, it appears they [do](https://github.com/pypa/packaging/blob/32deafe8668a2130a3366b98154914d188f3718e/src/packaging/utils.py#L37).

However, `packaging.requirements.Requirement` doesn't [use](https://github.com/pypa/packaging/blob/32deafe8668a2130a3366b98154914d188f3718e/src/packaging/_tokenizer.py#L82) `re.IGNORECASE`....so, even if you get such a package on to PyPI, it seems likely `pip` or another tool will reject it at some point.

2024-04-30 00:23 UTC, freakboy3742 requested changes
That's an odd discrepancy, but I can't argue with the practicality. A couple of minor clarification suggestions, including preserving the symmetry of the dotless-i test case.

2024-04-30 00:23 UTC, freakboy3742 commented on src/briefcase/config.py
>  # PEP508 provides a basic restriction on naming
```suggestion
# PEP 508 restricts the naming of modules. The PEP defines a regex that uses
# re.IGNORECASE; but in in practice, packaging uses a version that rolls out the lower
# case, which has very slightly different semantics with non-ASCII characters. This
# definition is the one from
# https://github.com/pypa/packaging/blob/24.0/src/packaging/_tokenizer.py#L80
```

2024-04-30 00:23 UTC, freakboy3742 commented on tests/config/test_is_valid_app_name.py
> +        "Kelvin",
```suggestion
        # ı, İ and K (i.e. 0x212a) are valid ASCII when made lowercase and as such are
        # accepted by the official PEP 508 regex... but they are rejected here to ensure
        # compliance with the regex that is used in practice.
        "helloworld_ı",
        "İstanbul",
        "Kelvin",
```

2024-04-30 03:07 UTC, freakboy3742 approved these changes

2024-04-30 03:08 UTC, merged