Normalize usage of newlines.
beeware/briefcase pull request #1769
Opened 2024-05-02 22:15 UTC by freakboy3742

#1766 included a newline cleanup that isn't entirely compatible with the line splitting approach being used.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2024-05-02 23:00 UTC, rmartin16 requested changes
Question about the vertical spacing.

Also, do you think the logging API might benefit from extra optional parameters that can insert vertical space before and after the content to log? This is a common pattern.

2024-05-02 23:13 UTC, freakboy3742 commented on changes/1769.misc.rst
> +The usage of newlines in a message was modified to be consistent with line autosplitting.
It will still bite my ass when I do the release on Monday, so I'll fix it now :-)

2024-05-02 23:14 UTC, freakboy3742 commented on src/briefcase/commands/create.py
>              for size, target in doctype.items():
Dang... the intention was to put a single break between the app icons and the document icons... but I forgot about the "there aren't any document icons" case. Fix incoming.

2024-05-02 23:14 UTC, freakboy3742 commented on src/briefcase/commands/create.py
>              for size, target in doctype.items():
I've opted to put the blank inside the outer loop; that means there will be a line break between the app icons and the first document icon (if there is one), and a break between each document icon group.

2024-05-03 00:11 UTC, rmartin16 approved these changes
looks good

2024-05-03 00:15 UTC, merged