Add a basic how-to for building apps in GitHub CI
beeware/briefcase pull request #1980
Opened 2024-08-30 18:34 UTC by rmartin16

## Changes
- First step to address #400
- This is mostly just the bare minimum workflow for using Briefcase in CI

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2024-08-31 00:15 UTC, freakboy3742 requested changes
+1 to the general direction of this. Yes, it's only covers the fairly obvious stuff, but that's an important first step. If we end up developing a re-usable action, then these instructions get simpler; but in the meantime, having *something* answers a moderately common question.

2024-08-31 00:15 UTC, freakboy3742 commented on docs/how-to/ci.rst
> +* Install Python 3.12
Should probably clarify that *this* example workflow uses 3.12, but you can use any support Python version.

2024-08-31 00:15 UTC, freakboy3742 commented on docs/how-to/ci.rst
> +configuration.
Could be explicit here about adding other platforms - "this sample packages for macOS, ...; if you wanted to add an Ubuntu 22.04 build, add another matrix entry " etc

2024-08-31 00:15 UTC, freakboy3742 commented on docs/how-to/ci.rst
> +            if: matrix.target != 'iOS'
Should clarify why this is with a comment.

2024-08-31 00:15 UTC, freakboy3742 commented on docs/how-to/ci.rst
> +* Upload the distributable artifact created for the platform
Configuring signing etc is ultimately an important step; we might want to (a) add a comment here that artefacts will be unsigned/adhoc-signed, and/or (b) put in a placeholder "how to configure signing" section heading with a link to the manual signing HOWTO instructions.

2024-08-31 00:15 UTC, freakboy3742 commented on changes/xxx.doc.rst
This can be 400.doc.rst; this is a direct response to the "document CI processes", even if it doesn't *completely* resolve that issue

2024-08-31 01:53 UTC, rmartin16 commented
Beefed this guide up a bit with your recommendations.

2024-08-31 01:59 UTC, rmartin16 commented
one more fix inbound; gonna move setting up KVM to `pre-command`...

2024-08-31 02:15 UTC, rmartin16 commented
All right; all edits done now :)

2024-09-01 23:28 UTC, freakboy3742 approved these changes
Looks great!

2024-09-01 23:28 UTC, merged