fix docker tag case sensitivity
beeware/briefcase pull request #475
Opened 2020-08-18 12:15 UTC by Czaki

Docker tag does not allow to use uppercase letter in tag. Python Package could have uppercase letters in name. 

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2020-08-18 12:34 UTC, Czaki commented
I do not understand this fail.

2020-08-18 23:05 UTC, freakboy3742 commented
The test that is failing is TownCrier - it's the system we use to help build release notes. See [the Briefcase contribution guide](https://briefcase.readthedocs.io/en/latest/how-to/contribute-code.html#add-change-information-for-release-notes) for details.

2020-08-19 00:22 UTC, freakboy3742 requested changes
The fix you've applied here looks good - however, we also need a test to verify that this behavior works as expected (and will remain working in future)

2020-09-02 21:50 UTC, Czaki commented
?

2020-09-06 01:42 UTC, freakboy3742 approved these changes
Apologies for the delay reviewing this - I've been busy with PyConline organisation. This looks great - thanks for the contribution!

2020-09-06 01:42 UTC, merged