moved package command arguments specific to macOs to base package
beeware/briefcase pull request #491
Opened 2020-09-17 10:35 UTC by ElijahAhianyo

Items completed in reference to #486 :
- moved signing options as a macOS specific extension on the app and dmg commands to reference docs for the package command
- moved package command arguments(adhoc,identity and no-sign) specific to macOs to the base package command

2020-09-17 23:22 UTC, freakboy3742 requested changes
Those code and docs changes look like exactly what we need - thanks!

One more tweak that is required (which is what the CI system is complaining about). Towncrier is the system we use to ensure that every change is included in the release notes; you'll need to drop a file named `changes/486.feature.rst` that gives a one line description of the new feature, as you'd expect to see it described in release notes (the number is the ticket you're solving; `.feature.` because it's new feature, rather than `bugfix`, `docs` or `misc`).

2020-09-18 00:52 UTC, freakboy3742 commented
Ah - now you're getting caught by coverage :-)

We have a test suite to make sure all the features of Briefcase continue to work as advertised; when we run the test suite, we measure which lines of code are executed. If you add some new code, but don't add a test, the coverage test fails (because you've presumably added functionality, but no tests).

In this case, you've removed code from the macOS app backend (increasing coverage, because there's less code to run); but you've added code to the package command - decreasing coverage. 

So - you'll need to add a test that exercises that code. 

For some reason, there actually aren't any tests of the base `package` command at present; you'll need to create some - including tests to verify that the three options you've added work as expected. The tests for the `run` command should give you an idea of the sort of thing that is required.

2020-09-20 20:05 UTC, ElijahAhianyo commented
whew. I did add some tests for the package command. Wasn't so sure if I covered all the required tests. If there's anything you think should be added, kindly let me know. If not, that was quite an interesting challenge and I'm glad to have contributed :)

2020-09-21 09:59 UTC, freakboy3742 approved these changes
Fantastic - those tests are exactly what we need! 

I'll make a couple of minor tweaks prior to merging There's no need to have *both* a doc and a feature change marker; and the text of the feature needs to be ready for inclusion in the release notes, so that means capitalisation, and talking more about what changes *functionally*, rather than the code that was changed. I also spotted a tiny typo in the test setup.

Thanks for the contribution - it's most appreciated!

2020-09-21 10:04 UTC, freakboy3742 commented
...and then I discover the hiccup. As you've submitted this PR from your master, rather than a branch, I can't push updates 😢 

It's generally good practice to work from a feature branch - it means you can have multiple PRs underway at the same time, and when the maintainer wants to push an update to your code, they can. 

In this case - the easiest fix will for me to give you the patch I wanted to apply:
```
diff --git a/changes/486.doc.rst b/changes/486.doc.rst
deleted file mode 100644
index d2d8569..0000000
--- a/changes/486.doc.rst
+++ /dev/null
@@ -1 +0,0 @@
-moved signing options as a macOS specific extension on the app and dmg commands to reference docs for the package command
\ No newline at end of file
diff --git a/changes/486.feature.rst b/changes/486.feature.rst
index 4df7c58..5b4d3ac 100644
--- a/changes/486.feature.rst
+++ b/changes/486.feature.rst
@@ -1 +1,2 @@
-moved package command arguments(adhoc,identity and no-sign) specific to macOs to the base package command
\ No newline at end of file
+Added signing options for all platforms. App signing is only implemented on
+macOS, but ``--no-sign`` can now be used regardless of your target platform.
diff --git a/tests/commands/package/conftest.py b/tests/commands/package/conftest.py
index 63e1231..0c008b6 100644
--- a/tests/commands/package/conftest.py
+++ b/tests/commands/package/conftest.py
@@ -7,7 +7,7 @@ from briefcase.config import AppConfig
 
 class DummyPackageCommand(PackageCommand):
     """
-    A dummy run command that doesn't actually do anything.
+    A dummy package command that doesn't actually do anything.
     It only serves to track which actions would be performend.
     """
     platform = 'tester'diff --git a/changes/486.doc.rst b/changes/486.doc.rst
deleted file mode 100644
index d2d8569..0000000
--- a/changes/486.doc.rst
+++ /dev/null
@@ -1 +0,0 @@
-moved signing options as a macOS specific extension on the app and dmg commands to reference docs for the package command
\ No newline at end of file
diff --git a/changes/486.feature.rst b/changes/486.feature.rst
index 4df7c58..5b4d3ac 100644
--- a/changes/486.feature.rst
+++ b/changes/486.feature.rst
@@ -1 +1,2 @@
-moved package command arguments(adhoc,identity and no-sign) specific to macOs to the base package command
\ No newline at end of file
+Added signing options for all platforms. App signing is only implemented on
+macOS, but ``--no-sign`` can now be used regardless of your target platform.
diff --git a/tests/commands/package/conftest.py b/tests/commands/package/conftest.py
index 63e1231..0c008b6 100644
--- a/tests/commands/package/conftest.py
+++ b/tests/commands/package/conftest.py
@@ -7,7 +7,7 @@ from briefcase.config import AppConfig
 
 class DummyPackageCommand(PackageCommand):
     """
-    A dummy run command that doesn't actually do anything.
+    A dummy package command that doesn't actually do anything.
     It only serves to track which actions would be performend.
     """
     platform = 'tester'
```
get you to make those changes, and update the PR.

For later PRs (there will be more PRs... right? 😄), making your edits in a branch will make this final tweak process much easier.

2020-09-21 12:41 UTC, ElijahAhianyo commented
Oh right. Thanks for the insight. If I'm getting you correctly, do I need to submit another PR(and closing this one) on a branch aside the master branch?

Also. Do I need to delete the doc change maker and modify the feature change marker as well?

Yes ! Of course there'll be more PRs. Looking forward to that

2020-09-24 06:17 UTC, freakboy3742 commented
You should delete the doc marker, and modify the existing feature marker with the text from the patch I provided.

At this point, it's probably easier to make the change on this PR, and keep the advice about PRs from branches for your next contribution.

2020-09-28 00:08 UTC, ElijahAhianyo commented
okay. i just did that

2020-09-28 01:34 UTC, freakboy3742 approved these changes
Awesome - thanks for the patch!

2020-09-28 01:34 UTC, merged