Improve check_output() usage and return value parsing
beeware/briefcase pull request #728
Opened 2022-05-02 21:49 UTC by rmartin16

In certain uses of `check_output`, issues can arise when processing the command output (as opposed to the command itself failing). Because the errors occur after `check_output` returns, the logging in #704 will not help users understand these errors.

These changes implement a new wrapper for `check_output` to invoke a supplied parser function on the command output. If the parsing fails, then the command, command output, and failure reason will be logged.

The calls to `simctl` on macOS were updated to use this new functionality.

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [ ] I will abide by the code of conduct

2022-05-02 23:42 UTC, rmartin16 commented
@freakboy3742, when you get a chance, I would appreciate your feedback on the high level decisions I've made in this PR.
 - Any tweaks to the check_output parsing?
 - Other `check_output` uses that should implement this?
   - After reviewing them, I didn't really see near as much value as with the `simctl` calls.
   - I initially get create a parser function for `AndroidSDK.devices()`.....but it felt a little overdone since it didn't ever seem likely to meaningfully fail there.
 - Yay or nay to `text=true`?
   - One concern I have is if `errors` or `encoding` need appropriate defaults as well.

Additionally, while I don't own any apple products, I was surprisingly able to finally get macOS running in a virtualbox vm. That'll hopefully let me get better familiarity with briefcase on macOS.

2022-05-03 01:34 UTC, freakboy3742 requested changes
tl;dr: this is looking really good.

The `text` change makes me a *little* twitchy, because it means the Briefcase subprocess shim isn't a 100% reproduction of the underlying API - but then, we're also adding environment wrappers, Docker wrappers, and now parsing functionality as well. On balance, I think it's the right thing to do (on the basis that every existing usage needs `text=True`, and you've provided an escape hatch on the off chance it *isn't* needed).

Your instinct/question around defaulting stderr->stdout is also a good one. On the one hand, almost every usage of check_output does this redirection; on the other hand, stray stderr output in parsed content may be one of the causes of parsing failure (and *not* redirecting would likely protect us from parsing errors). Ironically, the specific problem that caused this PR (the error that occurs once after an Xcode update) is impossible to reproduce, so I can't answer whether avoiding stderr redirection would actually be a fix for the problem. My inclination is to leave the redirection as is for now, and revisit it if/when we see consistent errors that we can attribute to stderr redirection.

I'm not sure I have any immediate suggestions of other parsers that should be added - The JSON parser is the only one that is a format that is re-used in multiple locations. The other places where check_output is being parsed tends to be "single purpose" - i.e., the parser would be used exactly once (for extracting a version number for a specific tool, or a list from the output of a specific tool). There might be a *minor* testing benefit from factoring out the parser from the invocation; but honestly, I'm not sure it's worth the code churn. 

As for the meat of the PR - the actual `parse_output()` function: Fundamentally, this looks great (and almost exactly what I would have expected to see). The only problem/issue I can see is around output related to error handling.

As currently implemented, invalid JSON output will:
* cause a JSON parsing error,
* raises a ParserError,
* is caught, causing `log.error` output,
* is raised as a CommandOutputParseError,
* is caught, and converted into a BriefcaseCommandError

The final error that is printed is a high-level "Unable to invoke simctl" or similar error. My concern is that the CommandOutputParseError is almost invisible; and a parsing error will manifest as a "can't run" command, rather than a "can't parse" error. The CommandOutputParseError should be caught independently to the CalledProcessError so that a different contextual error message can be output.

2022-05-03 23:38 UTC, rmartin16 commented on tests/integrations/subprocess/test_Subprocess__check_output.py
> -        universal_newlines=True
Added these tests for `run`, `check_output`, and `Popen`.

2022-05-03 23:47 UTC, rmartin16 commented
Updated to catch `CommandOutputParseError` so a different contextual error is presented to the user. And built out coverage for these changes. I also updated the `Subprocess` logging to ensure command outputs are strings.

I'm still trying to get the iOS simulator to work though....will submit once that's done.

2022-05-05 02:17 UTC, freakboy3742 approved these changes
Looks great. I've made a couple of minor cleanups on the way to landing - a couple of tuples that should be lists, plus some genericization of tests. 

The only change that is really substantial is the change in parameter ordering in parse_output - this is to ensure that the function can be curried/partialed (which isn't likely to be a common use case, but changing the order makes it at least possible).

Thanks for another great contribution!

2022-05-05 02:40 UTC, merged