Use absolute paths in requirements files
beeware/briefcase pull request #816
Opened 2022-08-08 20:12 UTC by mhsmith

Fixes #813. I had to use absolute paths in the end, because the Flatpak build moves the requirements file a second time before using it.

In order to get this working with Flatpak, the following additional changes were needed:
* https://github.com/beeware/briefcase-linux-flatpak-template/pull/4, so local requirement paths are visible to the Flatpak build process.
* Fixed Flatpak's override of the support package install method, which was broken by #805. This wasn't caught by the tests because they tested the behavior of the overridden low-level method, but not whether it was actually called. So I changed the tests to call a higher-level method.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2022-08-09 00:38 UTC, freakboy3742 requested changes
Good catch on the flatpak support package refactoring problem. Add that one to the list of problems that would have been caught if we actually ran apps as part of CI (See #699). 

One minor tweak regarding `os.path` vs `pathlib` which I've made on your behalf; and one larger problem with other valid inputs to requirements. I've reworked and extended the test cases to highlight the problem.

2022-08-09 20:40 UTC, mhsmith commented
Thanks, I'll look over this tomorrow.

2022-08-11 22:16 UTC, mhsmith commented on src/briefcase/commands/create.py
> +                            requirement = os.path.abspath(self.base_path / requirement)
I can't think of any benefit of resolving symbolic links here, but I can think of a potential problem. Consider the following sequence of events:
* The user adds a requirement path with a symlink, then runs `briefcase update -d`. A requirements.txt file is generated containing the symlink target path.
* The user changes the target of the symlink.
* The user runs `briefcase build`. The existing requirements.txt file is used, with the old symlink target.

The user's mental model is that their requirements list is passed directly to pip: the requirements file is just an implementation detail. So it's reasonable for them to assume that symlinks will be resolved by pip itself.

2022-08-12 00:46 UTC, freakboy3742 commented on src/briefcase/commands/create.py
> +                            requirement = os.path.abspath(self.base_path / requirement)
That's a reasonable point... I defaulted to "resolving references is a good thing"; but thinking about it some more, I think you're right that we should preserve the symlink, and let the last tool to *use* the link do the resolution.

2022-08-12 00:52 UTC, freakboy3742 approved these changes
👍 Nice work!

2022-08-12 01:03 UTC, merged