Fixed handling of missing model
beeware/briefcase pull request #876
Opened 2022-09-27 04:11 UTC by PrestonMclean

added a try block to catch keyError when an android device has no model.
[Fixes issue #820](https://github.com/beeware/briefcase/issues/820#issue-1335035232)

## PR Checklist:
- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2022-09-27 05:25 UTC, freakboy3742 requested changes
Looks good - a couple of cosmetic fixes, and a merge problem (looks like you forked this branch a couple of days ago before we landed #801, which was a big refactor of how we manage tools). 

One other note: you've submitted this pull request from your `main` branch. Ordinarily, if a PR was this close to being ready, I would make the final tweaks myself; however, because you've submitted from your `main` branch rather than a feature branch in your own fork, I can't make modifications to your pull request (your main branch is always protected from outside contributions).

It's generally a good idea to submit pull requests from a branch on your repository, rather than from you `main`; your `main` should usually be a direct copy of the upstream repository. This will save you a lot of headaches later when you come to do future pull requests (or, if you ever want to have multiple pull requests in flight at the same time).

2022-09-27 05:25 UTC, freakboy3742 commented on changes/820.bugfix
> +Fixed the handling of missing model
For consistency, this filename should be `820.bugfix.rst`

2022-09-27 05:25 UTC, freakboy3742 commented on tests/integrations/android_sdk/AndroidSDK/devices/no_model.out
> +emulator-5554          device product:sdk_phone_x86 device:generic_x86 transport_id:4
This file is missing a line ending; the real command output ends with a newline

2022-09-27 22:00 UTC, PrestonMclean commented
I made the changes, but I am having a problem with trailing white space for the pre-commit in test_devices.py.

2022-09-27 22:45 UTC, freakboy3742 requested changes
One small tweak for the release note, and we should be good to go.

Edit: Well, that and fixing the broken test :-)

2022-09-27 22:45 UTC, freakboy3742 commented on changes/820.bugfix.rst
> +Fixed the handling of missing model
This text is used as a release note, so it should be written in the past tense, in a way that anyone can understand it without context. Something like:

Android emulators that don't provide a model identifier can now be used to launch apps.

2022-09-28 01:41 UTC, freakboy3742 approved these changes
Looks great - Thanks for the PR!

2022-09-28 01:58 UTC, freakboy3742 commented
@PrestonMclean Not sure if that was an accident, but FYI - you don't need to do anything else on this PR; as soon as CI completes, I'll merge it, and it will be closed (as will the ticket for the bug it resolves).

2022-09-28 01:58 UTC, PrestonMclean commented
ok

2022-09-28 02:25 UTC, merged